### ISSUE TITLE
The login page cannot be displayed

### ISSUE THREAD

**Issue by lylJson** [making/oauth2-sso-demo#2]
![捕获](https://user-images.githubusercontent.com/34184776/92906872-6611dc00-f457-11ea-9993-5307ffe2fe57.PNG)

**Comment by making** [comment]
The screenshot doesn't help to see what is happening.

**Comment by lylJson** [comment]
I download the code and I run it in idea,and I visit  http://localhost:3000/ in chrome, then I connot be get the login page, but the http://127.0.0.1:9999/login with status 200 and as the picture I got the page, just not displayed,this is the log:
![捕获2](https://user-images.githubusercontent.com/34184776/92926262-56ea5880-f46e-11ea-9894-3083392b472f.PNG)
no error

**Comment by lylJson** [comment]
when the front get the page , how can I display in my chrome,I not familiar with js and react or other front-end framework

**Comment by making** [comment]
What do you want to do?
To get the app working, build jar files as documented and run each jar using `java -jar xxxx.jar`
https://github.com/making/oauth2-sso-demo#build

**Comment by lylJson** [comment]
emmm...，the java server is working in idea, when I visit you demo: https://todo.apps.pcfone.io, it displayed the login page,like this
![捕获4](https://user-images.githubusercontent.com/34184776/92928261-6ae38980-f471-11ea-8c0f-389d9c785c37.PNG)
 but when I visit my front:  http://localhost:3000/, I connot get the login page, I just want like you demo, displayed the login page.

**Comment by lylJson** [comment]
![捕获5](https://user-images.githubusercontent.com/34184776/92928515-c6157c00-f471-11ea-8dba-fe57e2507b08.PNG)

**Comment by making** [comment]
Go to localhost:8080 not 3000

Look my previous comment

**Comment by lylJson** [comment]
OK，got
